### ISSUE TITLE
Icons won't work with directive

### ISSUE THREAD

**Issue by jfsullivan** [blade-ui-kit/blade-heroicons#1] opened 2020-08-05 17:50 UTC
- Library Version: 0.1.2
- Laravel Version: 7.23.0
- PHP Version: 7.4.4

### Description:
Icons in the package work as expected when using the Laravel 7 component syntax but don't when using the @svg directive or helper.  The directive gives a "File does not exist at path" error with a path that ends at the Laravel base level.

### Steps To Reproduce:
1. Install the package in a Laravel project.
2. Add `<x-heroicon-o-adjustments/>` to a view to see the icon.
3. Add `@svg('heroicon-o-adjustments')` to a view and view the error.

**Comment by driesvints** [comment] 2020-08-05 19:00
Hey @jfsullivan. That works for me though. Have you tried `php artisan view:clear`? 

Going to close this as I can't reproduce it but feel free to reply.

**Closed by driesvints** 2020-08-05 19:00 UTC

**Comment by jfsullivan** [comment] 2020-08-05 21:03
Sorry for wasting your time.  I still had Adam Wathan's old SVG package in my composer file and it was causing the issue.  I removed it and ran `php artisan view:clear` and all worked fine.

Thanks for helping and for all of your work on Blade UI Kit packages.

**Comment by driesvints** [comment] 2020-08-06 08:12
Glad you got it sorted!
