### ISSUE TITLE
Unable to locate a class or view for component [heroicon-o-table]

### ISSUE THREAD

**Issue by adrian-ub** [blade-ui-kit/blade-heroicons#9] opened 2020-09-30 22:49 UTC
- Library Version: 0.2.2
- Laravel Version: v8.7.1
- PHP Version: 7.4.10

### Steps To Reproduce:

- Install the package in a Laravel project.
- Add `<x-heroicon-o-table/>` on view.
- Run `php artisan optimize`

```
 InvalidArgumentException

  Unable to locate a class or view for component [heroicon-o-table].
```

**Comment by driesvints** [comment] 2020-10-01 08:06
Did you run `php artisan view:clear`?

**Comment by adrian-ub** [comment] 2020-10-01 14:48
Yes

![image](https://user-images.githubusercontent.com/22903142/94824979-36595280-03cb-11eb-80b1-7ab53689fb57.png)

**Comment by driesvints** [comment] 2020-10-01 15:02
I'm running the package atm in several production apps with these specs so not really sure what's going on here. Can you reproduce this on a fresh install?

**Comment by driesvints** [comment] 2020-10-02 11:53
Thanks, I've managed to reproduce this. This seems to be a Laravel 8 specific problem. I'm a bit at a loss atm wat what's causing this but would greatly appreciate any help.

**Comment by dsturm** [comment] 2020-10-12 15:55
I ran into the same problem, **BUT** just to be sure: Did you install the `blade-ui-kit/blade-heroicons` or `blade-ui-kit/blade-icons` package? I first did the latter, which obviously was the problem 🙄.

Now after checking twice, with the `blade-ui-kit/blade-heroicons` package it runs well in a fresh Laravel 8 app. 🤦

**Comment by rizqyhi** [comment] 2020-10-18 13:40
I got the same problem after upgrading to Laravel 8. But in my case, the error happened on different icon:

```
InvalidArgumentException
Unable to locate a class or view for component [heroicon-o-camera].
```

**Comment by karlgray** [comment] 2020-10-18 21:01
> I ran into the same problem, **BUT** just to be sure: Did you install the `blade-ui-kit/blade-heroicons` or `blade-ui-kit/blade-icons` package? I first did the latter, which obviously was the problem roll_eyes.
> 
> Now after checking twice, with the `blade-ui-kit/blade-heroicons` package it runs well in a fresh Laravel 8 app. facepalm

This fixed it for me.  I removed both blade-heroicons and blade-icons.  Then just installed blade-heroicons.  Now working in Laravel 8.  Thanks.

**Comment by iksaku** [comment] 2020-11-23 05:32
Tested this and its working for me, I think its safe to close the issue while upgrading to the latest Laravel 8.x version :)

**Comment by driesvints** [comment] 2020-11-23 21:19
I also can't recreate it anymore on a fresh install so I'm closing this. Thanks all.

**Closed by driesvints** 2020-11-23 21:19 UTC
Labels: bug

**Comment by danielzzz** [comment] 2025-03-14 18:22
the same with v12. works locally but not in production. the weird thing is that if I execute optimize locally it would work in the same image that fails in production

**Comment by tanerkay** [comment] 2025-03-15 16:30
Also happens to me. On the base package `blade-ui-kit/blade-icons`. v1.8.0 on laravel 12. Fails locally and on CI.

Solution is to not run `php artisan optimize` and instead run all the optimize commands individually (painful).

Interestingly, this works:

```shell
php artisan config:cache
php artisan event:cache
php artisan route:cache
php artisan view:cache
php artisan icons:cache
```

Not sure what is happening differently when `php artisan optimize` is used.

<details>
<summary>Output:</summary>

```
   INFO  Caching framework bootstrap, configuration, and metadata.  

  config ...................................................... 23.93ms DONE
  events ....................................................... 1.57ms DONE
  routes ...................................................... 33.39ms DONE
  views ....................................................... 66.96ms FAIL

   InvalidArgumentException 

  Unable to locate a class or view for component [icon-link].

  at vendor/laravel/framework/src/Illuminate/View/Compilers/ComponentTagCompiler.php:316
    312▕         if (Str::startsWith($component, 'mail::')) {
    313▕             return $component;
    314▕         }
    315▕ 
  ➜ 316▕         throw new InvalidArgumentException(
    317▕             "Unable to locate a class or view for component [{$component}]."
    318▕         );
    319▕     }
    320▕ 

      +2 vendor frames 

  3   [internal]:0
      Illuminate\View\Compilers\ComponentTagCompiler::{closure:Illuminate\View\Compilers\ComponentTagCompiler::compileOpeningTags():152}()
      +7 vendor frames 

  11  [internal]:0
      Illuminate\Foundation\Console\ViewCacheCommand::{closure:Illuminate\Foundation\Console\ViewCacheCommand::compileViews():61}()
```
</details>

**Comment by citricguy** [comment] 2025-04-01 20:22
See: https://github.com/blade-ui-kit/blade-heroicons/issues/47

in Laravel 11/12 you need to comment out optimize and run the caches individually until fixed i believe to get around this.
# php artisan optimize

php artisan config:cache
php artisan event:cache
php artisan route:cache
php artisan view:cache
